// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRPServer.Model;

#nullable disable

namespace SRPServer.Migrations
{
    [DbContext(typeof(SRPContext))]
    [Migration("20221220081637_DB2")]
    partial class DB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SRPConfig.DriveConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GearRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("LargePulleyD")
                        .HasColumnType("REAL");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NominalN")
                        .HasColumnType("REAL");

                    b.Property<int>("PolesN")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SlipIdle")
                        .HasColumnType("REAL");

                    b.Property<double>("SlipNominal")
                        .HasColumnType("REAL");

                    b.Property<double>("SmallPulleyD")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DriveConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direction = true,
                            GearRatio = 0.0,
                            LargePulleyD = 1.6000000000000001,
                            Modified = false,
                            Name = "Drive1",
                            NominalN = 1.1000000000000001,
                            PolesN = 12,
                            SlipIdle = 1.3,
                            SlipNominal = 1.3999999999999999,
                            SmallPulleyD = 1.5
                        },
                        new
                        {
                            Id = 2,
                            Direction = true,
                            GearRatio = 0.0,
                            LargePulleyD = 2.6000000000000001,
                            Modified = false,
                            Name = "Drive2",
                            NominalN = 2.1000000000000001,
                            PolesN = 22,
                            SlipIdle = 2.2999999999999998,
                            SlipNominal = 2.3999999999999999,
                            SmallPulleyD = 2.5
                        },
                        new
                        {
                            Id = 3,
                            Direction = true,
                            GearRatio = 0.0,
                            LargePulleyD = 3.6000000000000001,
                            Modified = false,
                            Name = "Drive3",
                            NominalN = 3.1000000000000001,
                            PolesN = 32,
                            SlipIdle = 3.2999999999999998,
                            SlipNominal = 3.3999999999999999,
                            SmallPulleyD = 3.5
                        });
                });

            modelBuilder.Entity("SRPConfig.FluidConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GasFactor")
                        .HasColumnType("REAL");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OilDensity")
                        .HasColumnType("REAL");

                    b.Property<double>("WaterDensity")
                        .HasColumnType("REAL");

                    b.Property<double>("WaterHoldup")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FluidConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GasFactor = 1.3999999999999999,
                            Modified = false,
                            Name = "Fluid1",
                            OilDensity = 1.1000000000000001,
                            WaterDensity = 1.2,
                            WaterHoldup = 1.3
                        },
                        new
                        {
                            Id = 2,
                            GasFactor = 2.3999999999999999,
                            Modified = false,
                            Name = "Fluid2",
                            OilDensity = 2.1000000000000001,
                            WaterDensity = 2.2000000000000002,
                            WaterHoldup = 2.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            GasFactor = 3.3999999999999999,
                            Modified = false,
                            Name = "Fluid3",
                            OilDensity = 3.1000000000000001,
                            WaterDensity = 3.2000000000000002,
                            WaterHoldup = 3.2999999999999998
                        });
                });

            modelBuilder.Entity("SRPConfig.PUnitConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeamWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Counterweight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrankWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PUnitConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeamWidth = 44,
                            Counterweight = 0,
                            CrankWidth = 55,
                            Modified = false,
                            Name = "Unit1",
                            SizeA = 2000,
                            SizeC = 2000,
                            SizeG = 750,
                            SizeH = 3800,
                            SizeI = 2000,
                            SizeK = 2000,
                            SizeP = 3000,
                            SizeR = 1200
                        },
                        new
                        {
                            Id = 2,
                            BeamWidth = 45,
                            Counterweight = 0,
                            CrankWidth = 56,
                            Modified = false,
                            Name = "Unit2",
                            SizeA = 2001,
                            SizeC = 2001,
                            SizeG = 751,
                            SizeH = 3801,
                            SizeI = 2001,
                            SizeK = 2001,
                            SizeP = 3001,
                            SizeR = 1201
                        },
                        new
                        {
                            Id = 3,
                            BeamWidth = 46,
                            Counterweight = 0,
                            CrankWidth = 57,
                            Modified = false,
                            Name = "Unit3",
                            SizeA = 2002,
                            SizeC = 2002,
                            SizeG = 752,
                            SizeH = 3802,
                            SizeI = 2002,
                            SizeK = 2000,
                            SizeP = 3002,
                            SizeR = 1202
                        });
                });

            modelBuilder.Entity("SRPConfig.RodConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RodConfig");
                });

            modelBuilder.Entity("SRPConfig.RodSectionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("D")
                        .HasColumnType("REAL");

                    b.Property<double>("Density")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ModuleJung")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RodConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RodConfigId");

                    b.ToTable("RodSectionConfig");
                });

            modelBuilder.Entity("SRPConfig.SRPConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anchor")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Filling")
                        .HasColumnType("REAL");

                    b.Property<double>("FluidH")
                        .HasColumnType("REAL");

                    b.Property<double>("FrictionPlunger")
                        .HasColumnType("REAL");

                    b.Property<double>("FrictionSeal")
                        .HasColumnType("REAL");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PipeP")
                        .HasColumnType("REAL");

                    b.Property<double>("PlungerD")
                        .HasColumnType("REAL");

                    b.Property<double>("ZatrubP")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SRPConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anchor = false,
                            Filling = 1.3,
                            FluidH = 1.3999999999999999,
                            FrictionPlunger = 1.3999999999999999,
                            FrictionSeal = 1.3999999999999999,
                            Modified = false,
                            Name = "SRP1",
                            PipeP = 1.3999999999999999,
                            PlungerD = 1.2,
                            ZatrubP = 1.3999999999999999
                        },
                        new
                        {
                            Id = 2,
                            Anchor = false,
                            Filling = 2.2999999999999998,
                            FluidH = 2.3999999999999999,
                            FrictionPlunger = 2.3999999999999999,
                            FrictionSeal = 2.3999999999999999,
                            Modified = false,
                            Name = "SRP2",
                            PipeP = 2.3999999999999999,
                            PlungerD = 2.2000000000000002,
                            ZatrubP = 2.3999999999999999
                        },
                        new
                        {
                            Id = 3,
                            Anchor = false,
                            Filling = 3.2999999999999998,
                            FluidH = 3.3999999999999999,
                            FrictionPlunger = 3.3999999999999999,
                            FrictionSeal = 3.3999999999999999,
                            Modified = false,
                            Name = "SRP3",
                            PipeP = 3.3999999999999999,
                            PlungerD = 3.2000000000000002,
                            ZatrubP = 3.3999999999999999
                        });
                });

            modelBuilder.Entity("SRPConfig.TubingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Density")
                        .HasColumnType("REAL");

                    b.Property<double>("InnerD")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<bool>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ModuleJung")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OuterD")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TubingConfig");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Density = 1.2,
                            InnerD = 1.3999999999999999,
                            Length = 1.3999999999999999,
                            Modified = false,
                            ModuleJung = 1.1000000000000001,
                            Name = "Tubing1",
                            OuterD = 1.3999999999999999
                        },
                        new
                        {
                            Id = 2,
                            Density = 2.2000000000000002,
                            InnerD = 2.3999999999999999,
                            Length = 2.3999999999999999,
                            Modified = false,
                            ModuleJung = 2.1000000000000001,
                            Name = "Tubing2",
                            OuterD = 2.3999999999999999
                        },
                        new
                        {
                            Id = 3,
                            Density = 3.2000000000000002,
                            InnerD = 3.3999999999999999,
                            Length = 3.3999999999999999,
                            Modified = false,
                            ModuleJung = 3.1000000000000001,
                            Name = "Tubing3",
                            OuterD = 3.3999999999999999
                        });
                });

            modelBuilder.Entity("SRPConfig.RodSectionConfig", b =>
                {
                    b.HasOne("SRPConfig.RodConfig", null)
                        .WithMany("RodSectionConfigs")
                        .HasForeignKey("RodConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SRPConfig.RodConfig", b =>
                {
                    b.Navigation("RodSectionConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
